//
// Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
//
// On Mon Apr 18 18:32:50 EDT 2016
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1
// response_get                   O    24
// RDY_response_get               O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I     4
// EN_request_put                 I     1
// EN_response_get                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkSerializerBTP(CLK,
		       RST_N,

		       request_put,
		       EN_request_put,
		       RDY_request_put,

		       EN_response_get,
		       response_get,
		       RDY_response_get);
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [3 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [23 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [23 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // inlined wires
  wire [24 : 0] outputFIFO_enqReq_wires_0$wget;
  wire [4 : 0] inputFIFO_enqReq_wires_0$wget;
  wire outputFIFO_enqReq_wires_0$whas;

  // register byte_count
  reg [2 : 0] byte_count;
  wire [2 : 0] byte_count$D_IN;
  wire byte_count$EN;

  // register inputFIFO_clearReq_ehrReg
  reg inputFIFO_clearReq_ehrReg;
  wire inputFIFO_clearReq_ehrReg$D_IN, inputFIFO_clearReq_ehrReg$EN;

  // register inputFIFO_data_0
  reg [3 : 0] inputFIFO_data_0;
  wire [3 : 0] inputFIFO_data_0$D_IN;
  wire inputFIFO_data_0$EN;

  // register inputFIFO_data_1
  reg [3 : 0] inputFIFO_data_1;
  wire [3 : 0] inputFIFO_data_1$D_IN;
  wire inputFIFO_data_1$EN;

  // register inputFIFO_deqP
  reg inputFIFO_deqP;
  wire inputFIFO_deqP$D_IN, inputFIFO_deqP$EN;

  // register inputFIFO_deqReq_ehrReg
  reg inputFIFO_deqReq_ehrReg;
  wire inputFIFO_deqReq_ehrReg$D_IN, inputFIFO_deqReq_ehrReg$EN;

  // register inputFIFO_empty
  reg inputFIFO_empty;
  wire inputFIFO_empty$D_IN, inputFIFO_empty$EN;

  // register inputFIFO_enqP
  reg inputFIFO_enqP;
  wire inputFIFO_enqP$D_IN, inputFIFO_enqP$EN;

  // register inputFIFO_enqReq_ehrReg
  reg [4 : 0] inputFIFO_enqReq_ehrReg;
  wire [4 : 0] inputFIFO_enqReq_ehrReg$D_IN;
  wire inputFIFO_enqReq_ehrReg$EN;

  // register inputFIFO_full
  reg inputFIFO_full;
  wire inputFIFO_full$D_IN, inputFIFO_full$EN;

  // register outputFIFO_clearReq_ehrReg
  reg outputFIFO_clearReq_ehrReg;
  wire outputFIFO_clearReq_ehrReg$D_IN, outputFIFO_clearReq_ehrReg$EN;

  // register outputFIFO_data_0
  reg [23 : 0] outputFIFO_data_0;
  wire [23 : 0] outputFIFO_data_0$D_IN;
  wire outputFIFO_data_0$EN;

  // register outputFIFO_data_1
  reg [23 : 0] outputFIFO_data_1;
  wire [23 : 0] outputFIFO_data_1$D_IN;
  wire outputFIFO_data_1$EN;

  // register outputFIFO_deqP
  reg outputFIFO_deqP;
  wire outputFIFO_deqP$D_IN, outputFIFO_deqP$EN;

  // register outputFIFO_deqReq_ehrReg
  reg outputFIFO_deqReq_ehrReg;
  wire outputFIFO_deqReq_ehrReg$D_IN, outputFIFO_deqReq_ehrReg$EN;

  // register outputFIFO_empty
  reg outputFIFO_empty;
  wire outputFIFO_empty$D_IN, outputFIFO_empty$EN;

  // register outputFIFO_enqP
  reg outputFIFO_enqP;
  wire outputFIFO_enqP$D_IN, outputFIFO_enqP$EN;

  // register outputFIFO_enqReq_ehrReg
  reg [24 : 0] outputFIFO_enqReq_ehrReg;
  wire [24 : 0] outputFIFO_enqReq_ehrReg$D_IN;
  wire outputFIFO_enqReq_ehrReg$EN;

  // register outputFIFO_full
  reg outputFIFO_full;
  wire outputFIFO_full$D_IN, outputFIFO_full$EN;

  // register tempPixel_0
  reg [3 : 0] tempPixel_0;
  wire [3 : 0] tempPixel_0$D_IN;
  wire tempPixel_0$EN;

  // register tempPixel_1
  reg [3 : 0] tempPixel_1;
  reg [3 : 0] tempPixel_1$D_IN;
  wire tempPixel_1$EN;

  // register tempPixel_2
  reg [3 : 0] tempPixel_2;
  wire [3 : 0] tempPixel_2$D_IN;
  wire tempPixel_2$EN;

  // register tempPixel_3
  reg [3 : 0] tempPixel_3;
  wire [3 : 0] tempPixel_3$D_IN;
  wire tempPixel_3$EN;

  // register tempPixel_4
  reg [3 : 0] tempPixel_4;
  wire [3 : 0] tempPixel_4$D_IN;
  wire tempPixel_4$EN;

  // register tempPixel_5
  reg [3 : 0] tempPixel_5;
  wire [3 : 0] tempPixel_5$D_IN;
  wire tempPixel_5$EN;

  // ports of submodule inputFIFO_clearReq_virtual_reg_0
  wire inputFIFO_clearReq_virtual_reg_0$D_IN,
       inputFIFO_clearReq_virtual_reg_0$EN;

  // ports of submodule inputFIFO_clearReq_virtual_reg_1
  wire inputFIFO_clearReq_virtual_reg_1$D_IN,
       inputFIFO_clearReq_virtual_reg_1$EN,
       inputFIFO_clearReq_virtual_reg_1$Q_OUT;

  // ports of submodule inputFIFO_deqReq_virtual_reg_0
  wire inputFIFO_deqReq_virtual_reg_0$D_IN, inputFIFO_deqReq_virtual_reg_0$EN;

  // ports of submodule inputFIFO_deqReq_virtual_reg_1
  wire inputFIFO_deqReq_virtual_reg_1$D_IN, inputFIFO_deqReq_virtual_reg_1$EN;

  // ports of submodule inputFIFO_deqReq_virtual_reg_2
  wire inputFIFO_deqReq_virtual_reg_2$D_IN,
       inputFIFO_deqReq_virtual_reg_2$EN,
       inputFIFO_deqReq_virtual_reg_2$Q_OUT;

  // ports of submodule inputFIFO_enqReq_virtual_reg_0
  wire inputFIFO_enqReq_virtual_reg_0$D_IN, inputFIFO_enqReq_virtual_reg_0$EN;

  // ports of submodule inputFIFO_enqReq_virtual_reg_1
  wire inputFIFO_enqReq_virtual_reg_1$D_IN, inputFIFO_enqReq_virtual_reg_1$EN;

  // ports of submodule inputFIFO_enqReq_virtual_reg_2
  wire inputFIFO_enqReq_virtual_reg_2$D_IN,
       inputFIFO_enqReq_virtual_reg_2$EN,
       inputFIFO_enqReq_virtual_reg_2$Q_OUT;

  // ports of submodule outputFIFO_clearReq_virtual_reg_0
  wire outputFIFO_clearReq_virtual_reg_0$D_IN,
       outputFIFO_clearReq_virtual_reg_0$EN;

  // ports of submodule outputFIFO_clearReq_virtual_reg_1
  wire outputFIFO_clearReq_virtual_reg_1$D_IN,
       outputFIFO_clearReq_virtual_reg_1$EN,
       outputFIFO_clearReq_virtual_reg_1$Q_OUT;

  // ports of submodule outputFIFO_deqReq_virtual_reg_0
  wire outputFIFO_deqReq_virtual_reg_0$D_IN,
       outputFIFO_deqReq_virtual_reg_0$EN;

  // ports of submodule outputFIFO_deqReq_virtual_reg_1
  wire outputFIFO_deqReq_virtual_reg_1$D_IN,
       outputFIFO_deqReq_virtual_reg_1$EN;

  // ports of submodule outputFIFO_deqReq_virtual_reg_2
  wire outputFIFO_deqReq_virtual_reg_2$D_IN,
       outputFIFO_deqReq_virtual_reg_2$EN,
       outputFIFO_deqReq_virtual_reg_2$Q_OUT;

  // ports of submodule outputFIFO_enqReq_virtual_reg_0
  wire outputFIFO_enqReq_virtual_reg_0$D_IN,
       outputFIFO_enqReq_virtual_reg_0$EN;

  // ports of submodule outputFIFO_enqReq_virtual_reg_1
  wire outputFIFO_enqReq_virtual_reg_1$D_IN,
       outputFIFO_enqReq_virtual_reg_1$EN;

  // ports of submodule outputFIFO_enqReq_virtual_reg_2
  wire outputFIFO_enqReq_virtual_reg_2$D_IN,
       outputFIFO_enqReq_virtual_reg_2$EN,
       outputFIFO_enqReq_virtual_reg_2$Q_OUT;

  // rule scheduling signals
  wire CAN_FIRE_RL_bytetopixel,
       CAN_FIRE_RL_inputFIFO_canonicalize,
       CAN_FIRE_RL_inputFIFO_clearReq_canonicalize,
       CAN_FIRE_RL_inputFIFO_deqReq_canonicalize,
       CAN_FIRE_RL_inputFIFO_enqReq_canonicalize,
       CAN_FIRE_RL_outputFIFO_canonicalize,
       CAN_FIRE_RL_outputFIFO_clearReq_canonicalize,
       CAN_FIRE_RL_outputFIFO_deqReq_canonicalize,
       CAN_FIRE_RL_outputFIFO_enqReq_canonicalize,
       CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_RL_bytetopixel,
       WILL_FIRE_RL_inputFIFO_canonicalize,
       WILL_FIRE_RL_inputFIFO_clearReq_canonicalize,
       WILL_FIRE_RL_inputFIFO_deqReq_canonicalize,
       WILL_FIRE_RL_inputFIFO_enqReq_canonicalize,
       WILL_FIRE_RL_outputFIFO_canonicalize,
       WILL_FIRE_RL_outputFIFO_clearReq_canonicalize,
       WILL_FIRE_RL_outputFIFO_deqReq_canonicalize,
       WILL_FIRE_RL_outputFIFO_enqReq_canonicalize,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // remaining internal signals
  reg [3 : 0] CASE_inputFIFO_deqP_0_inputFIFO_data_0_1_input_ETC__q7,
	      CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q1,
	      CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q2,
	      CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q3,
	      CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q4,
	      CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q5,
	      CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q6;
  wire [23 : 0] IF_outputFIFO_enqReq_wires_1_whas__6_THEN_outp_ETC___d119;
  wire [15 : 0] SEL_ARR_outputFIFO_data_0_49_BITS_23_TO_20_50__ETC___d268;
  wire [3 : 0] IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d27;
  wire [2 : 0] x__h20950;
  wire IF_NOT_inputFIFO_deqReq_virtual_reg_2_read__2__ETC___d71,
       IF_NOT_inputFIFO_deqReq_virtual_reg_2_read__2__ETC___d74,
       IF_NOT_inputFIFO_enqReq_virtual_reg_2_read__3__ETC___d80,
       IF_NOT_outputFIFO_deqReq_virtual_reg_2_read__5_ETC___d163,
       IF_NOT_outputFIFO_deqReq_virtual_reg_2_read__5_ETC___d166,
       IF_NOT_outputFIFO_enqReq_virtual_reg_2_read__4_ETC___d172,
       IF_inputFIFO_deqReq_wires_1_whas__3_THEN_input_ETC___d39,
       IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d13,
       IF_outputFIFO_deqReq_wires_1_whas__25_THEN_out_ETC___d131,
       IF_outputFIFO_enqReq_wires_1_whas__6_THEN_outp_ETC___d105,
       _theResult_____2__h16853,
       _theResult_____2__h4974,
       inputFIFO_clearReq_virtual_reg_1_read__8_OR_IF_ETC___d52,
       next_deqP___1__h17258,
       next_deqP___1__h5379,
       outputFIFO_clearReq_virtual_reg_1_read__40_OR__ETC___d144,
       v__h12720,
       v__h13079,
       v__h4403,
       v__h4762;

  // action method request_put
  assign RDY_request_put = !inputFIFO_full ;
  assign CAN_FIRE_request_put = !inputFIFO_full ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get =
	     { SEL_ARR_outputFIFO_data_0_49_BITS_23_TO_20_50__ETC___d268,
	       CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q5,
	       CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q6 } ;
  assign RDY_response_get = !outputFIFO_empty ;
  assign CAN_FIRE_response_get = !outputFIFO_empty ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule inputFIFO_clearReq_virtual_reg_0
  RevertReg #(.width(32'd1),
	      .init(1'd0)) inputFIFO_clearReq_virtual_reg_0(.CLK(CLK),
							    .D_IN(inputFIFO_clearReq_virtual_reg_0$D_IN),
							    .EN(inputFIFO_clearReq_virtual_reg_0$EN),
							    .Q_OUT());

  // submodule inputFIFO_clearReq_virtual_reg_1
  RevertReg #(.width(32'd1),
	      .init(1'd0)) inputFIFO_clearReq_virtual_reg_1(.CLK(CLK),
							    .D_IN(inputFIFO_clearReq_virtual_reg_1$D_IN),
							    .EN(inputFIFO_clearReq_virtual_reg_1$EN),
							    .Q_OUT(inputFIFO_clearReq_virtual_reg_1$Q_OUT));

  // submodule inputFIFO_deqReq_virtual_reg_0
  RevertReg #(.width(32'd1),
	      .init(1'd0)) inputFIFO_deqReq_virtual_reg_0(.CLK(CLK),
							  .D_IN(inputFIFO_deqReq_virtual_reg_0$D_IN),
							  .EN(inputFIFO_deqReq_virtual_reg_0$EN),
							  .Q_OUT());

  // submodule inputFIFO_deqReq_virtual_reg_1
  RevertReg #(.width(32'd1),
	      .init(1'd0)) inputFIFO_deqReq_virtual_reg_1(.CLK(CLK),
							  .D_IN(inputFIFO_deqReq_virtual_reg_1$D_IN),
							  .EN(inputFIFO_deqReq_virtual_reg_1$EN),
							  .Q_OUT());

  // submodule inputFIFO_deqReq_virtual_reg_2
  RevertReg #(.width(32'd1),
	      .init(1'd0)) inputFIFO_deqReq_virtual_reg_2(.CLK(CLK),
							  .D_IN(inputFIFO_deqReq_virtual_reg_2$D_IN),
							  .EN(inputFIFO_deqReq_virtual_reg_2$EN),
							  .Q_OUT(inputFIFO_deqReq_virtual_reg_2$Q_OUT));

  // submodule inputFIFO_enqReq_virtual_reg_0
  RevertReg #(.width(32'd1),
	      .init(1'd0)) inputFIFO_enqReq_virtual_reg_0(.CLK(CLK),
							  .D_IN(inputFIFO_enqReq_virtual_reg_0$D_IN),
							  .EN(inputFIFO_enqReq_virtual_reg_0$EN),
							  .Q_OUT());

  // submodule inputFIFO_enqReq_virtual_reg_1
  RevertReg #(.width(32'd1),
	      .init(1'd0)) inputFIFO_enqReq_virtual_reg_1(.CLK(CLK),
							  .D_IN(inputFIFO_enqReq_virtual_reg_1$D_IN),
							  .EN(inputFIFO_enqReq_virtual_reg_1$EN),
							  .Q_OUT());

  // submodule inputFIFO_enqReq_virtual_reg_2
  RevertReg #(.width(32'd1),
	      .init(1'd0)) inputFIFO_enqReq_virtual_reg_2(.CLK(CLK),
							  .D_IN(inputFIFO_enqReq_virtual_reg_2$D_IN),
							  .EN(inputFIFO_enqReq_virtual_reg_2$EN),
							  .Q_OUT(inputFIFO_enqReq_virtual_reg_2$Q_OUT));

  // submodule outputFIFO_clearReq_virtual_reg_0
  RevertReg #(.width(32'd1),
	      .init(1'd0)) outputFIFO_clearReq_virtual_reg_0(.CLK(CLK),
							     .D_IN(outputFIFO_clearReq_virtual_reg_0$D_IN),
							     .EN(outputFIFO_clearReq_virtual_reg_0$EN),
							     .Q_OUT());

  // submodule outputFIFO_clearReq_virtual_reg_1
  RevertReg #(.width(32'd1),
	      .init(1'd0)) outputFIFO_clearReq_virtual_reg_1(.CLK(CLK),
							     .D_IN(outputFIFO_clearReq_virtual_reg_1$D_IN),
							     .EN(outputFIFO_clearReq_virtual_reg_1$EN),
							     .Q_OUT(outputFIFO_clearReq_virtual_reg_1$Q_OUT));

  // submodule outputFIFO_deqReq_virtual_reg_0
  RevertReg #(.width(32'd1),
	      .init(1'd0)) outputFIFO_deqReq_virtual_reg_0(.CLK(CLK),
							   .D_IN(outputFIFO_deqReq_virtual_reg_0$D_IN),
							   .EN(outputFIFO_deqReq_virtual_reg_0$EN),
							   .Q_OUT());

  // submodule outputFIFO_deqReq_virtual_reg_1
  RevertReg #(.width(32'd1),
	      .init(1'd0)) outputFIFO_deqReq_virtual_reg_1(.CLK(CLK),
							   .D_IN(outputFIFO_deqReq_virtual_reg_1$D_IN),
							   .EN(outputFIFO_deqReq_virtual_reg_1$EN),
							   .Q_OUT());

  // submodule outputFIFO_deqReq_virtual_reg_2
  RevertReg #(.width(32'd1),
	      .init(1'd0)) outputFIFO_deqReq_virtual_reg_2(.CLK(CLK),
							   .D_IN(outputFIFO_deqReq_virtual_reg_2$D_IN),
							   .EN(outputFIFO_deqReq_virtual_reg_2$EN),
							   .Q_OUT(outputFIFO_deqReq_virtual_reg_2$Q_OUT));

  // submodule outputFIFO_enqReq_virtual_reg_0
  RevertReg #(.width(32'd1),
	      .init(1'd0)) outputFIFO_enqReq_virtual_reg_0(.CLK(CLK),
							   .D_IN(outputFIFO_enqReq_virtual_reg_0$D_IN),
							   .EN(outputFIFO_enqReq_virtual_reg_0$EN),
							   .Q_OUT());

  // submodule outputFIFO_enqReq_virtual_reg_1
  RevertReg #(.width(32'd1),
	      .init(1'd0)) outputFIFO_enqReq_virtual_reg_1(.CLK(CLK),
							   .D_IN(outputFIFO_enqReq_virtual_reg_1$D_IN),
							   .EN(outputFIFO_enqReq_virtual_reg_1$EN),
							   .Q_OUT());

  // submodule outputFIFO_enqReq_virtual_reg_2
  RevertReg #(.width(32'd1),
	      .init(1'd0)) outputFIFO_enqReq_virtual_reg_2(.CLK(CLK),
							   .D_IN(outputFIFO_enqReq_virtual_reg_2$D_IN),
							   .EN(outputFIFO_enqReq_virtual_reg_2$EN),
							   .Q_OUT(outputFIFO_enqReq_virtual_reg_2$Q_OUT));

  // rule RL_bytetopixel
  assign CAN_FIRE_RL_bytetopixel =
	     !inputFIFO_empty && (byte_count != 3'd5 || !outputFIFO_full) ;
  assign WILL_FIRE_RL_bytetopixel = CAN_FIRE_RL_bytetopixel ;

  // rule RL_inputFIFO_canonicalize
  assign CAN_FIRE_RL_inputFIFO_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_inputFIFO_canonicalize = 1'd1 ;

  // rule RL_inputFIFO_enqReq_canonicalize
  assign CAN_FIRE_RL_inputFIFO_enqReq_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_inputFIFO_enqReq_canonicalize = 1'd1 ;

  // rule RL_inputFIFO_deqReq_canonicalize
  assign CAN_FIRE_RL_inputFIFO_deqReq_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_inputFIFO_deqReq_canonicalize = 1'd1 ;

  // rule RL_inputFIFO_clearReq_canonicalize
  assign CAN_FIRE_RL_inputFIFO_clearReq_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_inputFIFO_clearReq_canonicalize = 1'd1 ;

  // rule RL_outputFIFO_canonicalize
  assign CAN_FIRE_RL_outputFIFO_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_outputFIFO_canonicalize = 1'd1 ;

  // rule RL_outputFIFO_enqReq_canonicalize
  assign CAN_FIRE_RL_outputFIFO_enqReq_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_outputFIFO_enqReq_canonicalize = 1'd1 ;

  // rule RL_outputFIFO_deqReq_canonicalize
  assign CAN_FIRE_RL_outputFIFO_deqReq_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_outputFIFO_deqReq_canonicalize = 1'd1 ;

  // rule RL_outputFIFO_clearReq_canonicalize
  assign CAN_FIRE_RL_outputFIFO_clearReq_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_outputFIFO_clearReq_canonicalize = 1'd1 ;

  // inlined wires
  assign inputFIFO_enqReq_wires_0$wget = { 1'd1, request_put } ;
  assign outputFIFO_enqReq_wires_0$wget =
	     { 1'd1,
	       CASE_inputFIFO_deqP_0_inputFIFO_data_0_1_input_ETC__q7,
	       tempPixel_4,
	       tempPixel_3,
	       tempPixel_2,
	       tempPixel_1,
	       tempPixel_0 } ;
  assign outputFIFO_enqReq_wires_0$whas =
	     WILL_FIRE_RL_bytetopixel && byte_count == 3'd5 ;

  // register byte_count
  assign byte_count$D_IN = (byte_count == 3'd5) ? 3'd0 : x__h20950 ;
  assign byte_count$EN = CAN_FIRE_RL_bytetopixel ;

  // register inputFIFO_clearReq_ehrReg
  assign inputFIFO_clearReq_ehrReg$D_IN = 1'd0 ;
  assign inputFIFO_clearReq_ehrReg$EN = 1'd1 ;

  // register inputFIFO_data_0
  assign inputFIFO_data_0$D_IN =
	     IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d27 ;
  assign inputFIFO_data_0$EN =
	     inputFIFO_enqP == 1'd0 &&
	     inputFIFO_clearReq_virtual_reg_1_read__8_OR_IF_ETC___d52 &&
	     !inputFIFO_enqReq_virtual_reg_2$Q_OUT &&
	     IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d13 ;

  // register inputFIFO_data_1
  assign inputFIFO_data_1$D_IN =
	     IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d27 ;
  assign inputFIFO_data_1$EN =
	     inputFIFO_enqP == 1'd1 &&
	     inputFIFO_clearReq_virtual_reg_1_read__8_OR_IF_ETC___d52 &&
	     !inputFIFO_enqReq_virtual_reg_2$Q_OUT &&
	     IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d13 ;

  // register inputFIFO_deqP
  assign inputFIFO_deqP$D_IN =
	     inputFIFO_clearReq_virtual_reg_1_read__8_OR_IF_ETC___d52 &&
	     _theResult_____2__h4974 ;
  assign inputFIFO_deqP$EN = 1'd1 ;

  // register inputFIFO_deqReq_ehrReg
  assign inputFIFO_deqReq_ehrReg$D_IN = 1'd0 ;
  assign inputFIFO_deqReq_ehrReg$EN = 1'd1 ;

  // register inputFIFO_empty
  assign inputFIFO_empty$D_IN =
	     !inputFIFO_clearReq_virtual_reg_1$Q_OUT &&
	     inputFIFO_clearReq_ehrReg ||
	     IF_NOT_inputFIFO_deqReq_virtual_reg_2_read__2__ETC___d71 &&
	     IF_NOT_inputFIFO_enqReq_virtual_reg_2_read__3__ETC___d80 ;
  assign inputFIFO_empty$EN = 1'd1 ;

  // register inputFIFO_enqP
  assign inputFIFO_enqP$D_IN =
	     inputFIFO_clearReq_virtual_reg_1_read__8_OR_IF_ETC___d52 &&
	     v__h4403 ;
  assign inputFIFO_enqP$EN = 1'd1 ;

  // register inputFIFO_enqReq_ehrReg
  assign inputFIFO_enqReq_ehrReg$D_IN = 5'b01010 ;
  assign inputFIFO_enqReq_ehrReg$EN = 1'd1 ;

  // register inputFIFO_full
  assign inputFIFO_full$D_IN =
	     inputFIFO_clearReq_virtual_reg_1_read__8_OR_IF_ETC___d52 &&
	     IF_NOT_inputFIFO_deqReq_virtual_reg_2_read__2__ETC___d74 ;
  assign inputFIFO_full$EN = 1'd1 ;

  // register outputFIFO_clearReq_ehrReg
  assign outputFIFO_clearReq_ehrReg$D_IN = 1'd0 ;
  assign outputFIFO_clearReq_ehrReg$EN = 1'd1 ;

  // register outputFIFO_data_0
  assign outputFIFO_data_0$D_IN =
	     (outputFIFO_enqReq_virtual_reg_2$Q_OUT ||
	      (outputFIFO_enqReq_wires_0$whas ?
		 !outputFIFO_enqReq_wires_0$wget[24] :
		 !outputFIFO_enqReq_ehrReg[24])) ?
	       { outputFIFO_enqReq_wires_0$whas ?
		   outputFIFO_enqReq_wires_0$wget[23:20] :
		   outputFIFO_enqReq_ehrReg[23:20],
		 outputFIFO_enqReq_wires_0$whas ?
		   outputFIFO_enqReq_wires_0$wget[19:16] :
		   outputFIFO_enqReq_ehrReg[19:16],
		 outputFIFO_enqReq_wires_0$whas ?
		   outputFIFO_enqReq_wires_0$wget[15:12] :
		   outputFIFO_enqReq_ehrReg[15:12],
		 outputFIFO_enqReq_wires_0$whas ?
		   outputFIFO_enqReq_wires_0$wget[11:8] :
		   outputFIFO_enqReq_ehrReg[11:8],
		 outputFIFO_enqReq_wires_0$whas ?
		   outputFIFO_enqReq_wires_0$wget[7:4] :
		   outputFIFO_enqReq_ehrReg[7:4],
		 outputFIFO_enqReq_wires_0$whas ?
		   outputFIFO_enqReq_wires_0$wget[3:0] :
		   outputFIFO_enqReq_ehrReg[3:0] } :
	       IF_outputFIFO_enqReq_wires_1_whas__6_THEN_outp_ETC___d119 ;
  assign outputFIFO_data_0$EN =
	     outputFIFO_enqP == 1'd0 &&
	     outputFIFO_clearReq_virtual_reg_1_read__40_OR__ETC___d144 &&
	     !outputFIFO_enqReq_virtual_reg_2$Q_OUT &&
	     IF_outputFIFO_enqReq_wires_1_whas__6_THEN_outp_ETC___d105 ;

  // register outputFIFO_data_1
  assign outputFIFO_data_1$D_IN = outputFIFO_data_0$D_IN ;
  assign outputFIFO_data_1$EN =
	     outputFIFO_enqP == 1'd1 &&
	     outputFIFO_clearReq_virtual_reg_1_read__40_OR__ETC___d144 &&
	     !outputFIFO_enqReq_virtual_reg_2$Q_OUT &&
	     IF_outputFIFO_enqReq_wires_1_whas__6_THEN_outp_ETC___d105 ;

  // register outputFIFO_deqP
  assign outputFIFO_deqP$D_IN =
	     outputFIFO_clearReq_virtual_reg_1_read__40_OR__ETC___d144 &&
	     _theResult_____2__h16853 ;
  assign outputFIFO_deqP$EN = 1'd1 ;

  // register outputFIFO_deqReq_ehrReg
  assign outputFIFO_deqReq_ehrReg$D_IN = 1'd0 ;
  assign outputFIFO_deqReq_ehrReg$EN = 1'd1 ;

  // register outputFIFO_empty
  assign outputFIFO_empty$D_IN =
	     !outputFIFO_clearReq_virtual_reg_1$Q_OUT &&
	     outputFIFO_clearReq_ehrReg ||
	     IF_NOT_outputFIFO_deqReq_virtual_reg_2_read__5_ETC___d163 &&
	     IF_NOT_outputFIFO_enqReq_virtual_reg_2_read__4_ETC___d172 ;
  assign outputFIFO_empty$EN = 1'd1 ;

  // register outputFIFO_enqP
  assign outputFIFO_enqP$D_IN =
	     outputFIFO_clearReq_virtual_reg_1_read__40_OR__ETC___d144 &&
	     v__h12720 ;
  assign outputFIFO_enqP$EN = 1'd1 ;

  // register outputFIFO_enqReq_ehrReg
  assign outputFIFO_enqReq_ehrReg$D_IN = 25'b0101010101010101010101010 ;
  assign outputFIFO_enqReq_ehrReg$EN = 1'd1 ;

  // register outputFIFO_full
  assign outputFIFO_full$D_IN =
	     outputFIFO_clearReq_virtual_reg_1_read__40_OR__ETC___d144 &&
	     IF_NOT_outputFIFO_deqReq_virtual_reg_2_read__5_ETC___d166 ;
  assign outputFIFO_full$EN = 1'd1 ;

  // register tempPixel_0
  assign tempPixel_0$D_IN = tempPixel_1$D_IN ;
  assign tempPixel_0$EN = WILL_FIRE_RL_bytetopixel && byte_count == 3'd0 ;

  // register tempPixel_1
  always@(inputFIFO_deqP or inputFIFO_data_0 or inputFIFO_data_1)
  begin
    case (inputFIFO_deqP)
      1'd0: tempPixel_1$D_IN = inputFIFO_data_0;
      1'd1: tempPixel_1$D_IN = inputFIFO_data_1;
    endcase
  end
  assign tempPixel_1$EN = WILL_FIRE_RL_bytetopixel && byte_count == 3'd1 ;

  // register tempPixel_2
  assign tempPixel_2$D_IN = tempPixel_1$D_IN ;
  assign tempPixel_2$EN = WILL_FIRE_RL_bytetopixel && byte_count == 3'd2 ;

  // register tempPixel_3
  assign tempPixel_3$D_IN = tempPixel_1$D_IN ;
  assign tempPixel_3$EN = WILL_FIRE_RL_bytetopixel && byte_count == 3'd3 ;

  // register tempPixel_4
  assign tempPixel_4$D_IN = tempPixel_1$D_IN ;
  assign tempPixel_4$EN = WILL_FIRE_RL_bytetopixel && byte_count == 3'd4 ;

  // register tempPixel_5
  assign tempPixel_5$D_IN = tempPixel_1$D_IN ;
  assign tempPixel_5$EN = outputFIFO_enqReq_wires_0$whas ;

  // submodule inputFIFO_clearReq_virtual_reg_0
  assign inputFIFO_clearReq_virtual_reg_0$D_IN = 1'b0 ;
  assign inputFIFO_clearReq_virtual_reg_0$EN = 1'b0 ;

  // submodule inputFIFO_clearReq_virtual_reg_1
  assign inputFIFO_clearReq_virtual_reg_1$D_IN = 1'd0 ;
  assign inputFIFO_clearReq_virtual_reg_1$EN = 1'd1 ;

  // submodule inputFIFO_deqReq_virtual_reg_0
  assign inputFIFO_deqReq_virtual_reg_0$D_IN = 1'd0 ;
  assign inputFIFO_deqReq_virtual_reg_0$EN = CAN_FIRE_RL_bytetopixel ;

  // submodule inputFIFO_deqReq_virtual_reg_1
  assign inputFIFO_deqReq_virtual_reg_1$D_IN = 1'b0 ;
  assign inputFIFO_deqReq_virtual_reg_1$EN = 1'b0 ;

  // submodule inputFIFO_deqReq_virtual_reg_2
  assign inputFIFO_deqReq_virtual_reg_2$D_IN = 1'd0 ;
  assign inputFIFO_deqReq_virtual_reg_2$EN = 1'd1 ;

  // submodule inputFIFO_enqReq_virtual_reg_0
  assign inputFIFO_enqReq_virtual_reg_0$D_IN = 1'd0 ;
  assign inputFIFO_enqReq_virtual_reg_0$EN = EN_request_put ;

  // submodule inputFIFO_enqReq_virtual_reg_1
  assign inputFIFO_enqReq_virtual_reg_1$D_IN = 1'b0 ;
  assign inputFIFO_enqReq_virtual_reg_1$EN = 1'b0 ;

  // submodule inputFIFO_enqReq_virtual_reg_2
  assign inputFIFO_enqReq_virtual_reg_2$D_IN = 1'd0 ;
  assign inputFIFO_enqReq_virtual_reg_2$EN = 1'd1 ;

  // submodule outputFIFO_clearReq_virtual_reg_0
  assign outputFIFO_clearReq_virtual_reg_0$D_IN = 1'b0 ;
  assign outputFIFO_clearReq_virtual_reg_0$EN = 1'b0 ;

  // submodule outputFIFO_clearReq_virtual_reg_1
  assign outputFIFO_clearReq_virtual_reg_1$D_IN = 1'd0 ;
  assign outputFIFO_clearReq_virtual_reg_1$EN = 1'd1 ;

  // submodule outputFIFO_deqReq_virtual_reg_0
  assign outputFIFO_deqReq_virtual_reg_0$D_IN = 1'd0 ;
  assign outputFIFO_deqReq_virtual_reg_0$EN = EN_response_get ;

  // submodule outputFIFO_deqReq_virtual_reg_1
  assign outputFIFO_deqReq_virtual_reg_1$D_IN = 1'b0 ;
  assign outputFIFO_deqReq_virtual_reg_1$EN = 1'b0 ;

  // submodule outputFIFO_deqReq_virtual_reg_2
  assign outputFIFO_deqReq_virtual_reg_2$D_IN = 1'd0 ;
  assign outputFIFO_deqReq_virtual_reg_2$EN = 1'd1 ;

  // submodule outputFIFO_enqReq_virtual_reg_0
  assign outputFIFO_enqReq_virtual_reg_0$D_IN = 1'd0 ;
  assign outputFIFO_enqReq_virtual_reg_0$EN = outputFIFO_enqReq_wires_0$whas ;

  // submodule outputFIFO_enqReq_virtual_reg_1
  assign outputFIFO_enqReq_virtual_reg_1$D_IN = 1'b0 ;
  assign outputFIFO_enqReq_virtual_reg_1$EN = 1'b0 ;

  // submodule outputFIFO_enqReq_virtual_reg_2
  assign outputFIFO_enqReq_virtual_reg_2$D_IN = 1'd0 ;
  assign outputFIFO_enqReq_virtual_reg_2$EN = 1'd1 ;

  // remaining internal signals
  assign IF_NOT_inputFIFO_deqReq_virtual_reg_2_read__2__ETC___d71 =
	     _theResult_____2__h4974 == v__h4403 ;
  assign IF_NOT_inputFIFO_deqReq_virtual_reg_2_read__2__ETC___d74 =
	     IF_NOT_inputFIFO_deqReq_virtual_reg_2_read__2__ETC___d71 &&
	     (!inputFIFO_enqReq_virtual_reg_2$Q_OUT &&
	      IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d13 ||
	      inputFIFO_full) ;
  assign IF_NOT_inputFIFO_enqReq_virtual_reg_2_read__3__ETC___d80 =
	     (!inputFIFO_enqReq_virtual_reg_2$Q_OUT &&
	      IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d13) ?
	       inputFIFO_empty :
	       !inputFIFO_deqReq_virtual_reg_2$Q_OUT &&
	       IF_inputFIFO_deqReq_wires_1_whas__3_THEN_input_ETC___d39 ||
	       inputFIFO_empty ;
  assign IF_NOT_outputFIFO_deqReq_virtual_reg_2_read__5_ETC___d163 =
	     _theResult_____2__h16853 == v__h12720 ;
  assign IF_NOT_outputFIFO_deqReq_virtual_reg_2_read__5_ETC___d166 =
	     IF_NOT_outputFIFO_deqReq_virtual_reg_2_read__5_ETC___d163 &&
	     (!outputFIFO_enqReq_virtual_reg_2$Q_OUT &&
	      IF_outputFIFO_enqReq_wires_1_whas__6_THEN_outp_ETC___d105 ||
	      outputFIFO_full) ;
  assign IF_NOT_outputFIFO_enqReq_virtual_reg_2_read__4_ETC___d172 =
	     (!outputFIFO_enqReq_virtual_reg_2$Q_OUT &&
	      IF_outputFIFO_enqReq_wires_1_whas__6_THEN_outp_ETC___d105) ?
	       outputFIFO_empty :
	       !outputFIFO_deqReq_virtual_reg_2$Q_OUT &&
	       IF_outputFIFO_deqReq_wires_1_whas__25_THEN_out_ETC___d131 ||
	       outputFIFO_empty ;
  assign IF_inputFIFO_deqReq_wires_1_whas__3_THEN_input_ETC___d39 =
	     CAN_FIRE_RL_bytetopixel || inputFIFO_deqReq_ehrReg ;
  assign IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d13 =
	     EN_request_put ?
	       inputFIFO_enqReq_wires_0$wget[4] :
	       inputFIFO_enqReq_ehrReg[4] ;
  assign IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d27 =
	     EN_request_put ?
	       inputFIFO_enqReq_wires_0$wget[3:0] :
	       inputFIFO_enqReq_ehrReg[3:0] ;
  assign IF_outputFIFO_deqReq_wires_1_whas__25_THEN_out_ETC___d131 =
	     EN_response_get || outputFIFO_deqReq_ehrReg ;
  assign IF_outputFIFO_enqReq_wires_1_whas__6_THEN_outp_ETC___d105 =
	     outputFIFO_enqReq_wires_0$whas ?
	       outputFIFO_enqReq_wires_0$wget[24] :
	       outputFIFO_enqReq_ehrReg[24] ;
  assign IF_outputFIFO_enqReq_wires_1_whas__6_THEN_outp_ETC___d119 =
	     outputFIFO_enqReq_wires_0$whas ?
	       outputFIFO_enqReq_wires_0$wget[23:0] :
	       outputFIFO_enqReq_ehrReg[23:0] ;
  assign SEL_ARR_outputFIFO_data_0_49_BITS_23_TO_20_50__ETC___d268 =
	     { CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q1,
	       CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q2,
	       CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q3,
	       CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q4 } ;
  assign _theResult_____2__h16853 =
	     (!outputFIFO_deqReq_virtual_reg_2$Q_OUT &&
	      IF_outputFIFO_deqReq_wires_1_whas__25_THEN_out_ETC___d131) ?
	       next_deqP___1__h17258 :
	       outputFIFO_deqP ;
  assign _theResult_____2__h4974 =
	     (!inputFIFO_deqReq_virtual_reg_2$Q_OUT &&
	      IF_inputFIFO_deqReq_wires_1_whas__3_THEN_input_ETC___d39) ?
	       next_deqP___1__h5379 :
	       inputFIFO_deqP ;
  assign inputFIFO_clearReq_virtual_reg_1_read__8_OR_IF_ETC___d52 =
	     inputFIFO_clearReq_virtual_reg_1$Q_OUT ||
	     !inputFIFO_clearReq_ehrReg ;
  assign next_deqP___1__h17258 = outputFIFO_deqP + 1'd1 ;
  assign next_deqP___1__h5379 = inputFIFO_deqP + 1'd1 ;
  assign outputFIFO_clearReq_virtual_reg_1_read__40_OR__ETC___d144 =
	     outputFIFO_clearReq_virtual_reg_1$Q_OUT ||
	     !outputFIFO_clearReq_ehrReg ;
  assign v__h12720 =
	     (!outputFIFO_enqReq_virtual_reg_2$Q_OUT &&
	      IF_outputFIFO_enqReq_wires_1_whas__6_THEN_outp_ETC___d105) ?
	       v__h13079 :
	       outputFIFO_enqP ;
  assign v__h13079 = outputFIFO_enqP + 1'd1 ;
  assign v__h4403 =
	     (!inputFIFO_enqReq_virtual_reg_2$Q_OUT &&
	      IF_inputFIFO_enqReq_wires_1_whas_THEN_inputFIF_ETC___d13) ?
	       v__h4762 :
	       inputFIFO_enqP ;
  assign v__h4762 = inputFIFO_enqP + 1'd1 ;
  assign x__h20950 = byte_count + 3'd1 ;
  always@(outputFIFO_deqP or outputFIFO_data_0 or outputFIFO_data_1)
  begin
    case (outputFIFO_deqP)
      1'd0:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q1 =
	      outputFIFO_data_0[23:20];
      1'd1:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q1 =
	      outputFIFO_data_1[23:20];
    endcase
  end
  always@(outputFIFO_deqP or outputFIFO_data_0 or outputFIFO_data_1)
  begin
    case (outputFIFO_deqP)
      1'd0:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q2 =
	      outputFIFO_data_0[19:16];
      1'd1:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q2 =
	      outputFIFO_data_1[19:16];
    endcase
  end
  always@(outputFIFO_deqP or outputFIFO_data_0 or outputFIFO_data_1)
  begin
    case (outputFIFO_deqP)
      1'd0:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q3 =
	      outputFIFO_data_0[15:12];
      1'd1:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q3 =
	      outputFIFO_data_1[15:12];
    endcase
  end
  always@(outputFIFO_deqP or outputFIFO_data_0 or outputFIFO_data_1)
  begin
    case (outputFIFO_deqP)
      1'd0:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q4 =
	      outputFIFO_data_0[11:8];
      1'd1:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q4 =
	      outputFIFO_data_1[11:8];
    endcase
  end
  always@(outputFIFO_deqP or outputFIFO_data_0 or outputFIFO_data_1)
  begin
    case (outputFIFO_deqP)
      1'd0:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q5 =
	      outputFIFO_data_0[7:4];
      1'd1:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q5 =
	      outputFIFO_data_1[7:4];
    endcase
  end
  always@(outputFIFO_deqP or outputFIFO_data_0 or outputFIFO_data_1)
  begin
    case (outputFIFO_deqP)
      1'd0:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q6 =
	      outputFIFO_data_0[3:0];
      1'd1:
	  CASE_outputFIFO_deqP_0_outputFIFO_data_0_BITS__ETC__q6 =
	      outputFIFO_data_1[3:0];
    endcase
  end
  always@(inputFIFO_deqP or inputFIFO_data_0 or inputFIFO_data_1)
  begin
    case (inputFIFO_deqP)
      1'd0:
	  CASE_inputFIFO_deqP_0_inputFIFO_data_0_1_input_ETC__q7 =
	      inputFIFO_data_0;
      1'd1:
	  CASE_inputFIFO_deqP_0_inputFIFO_data_0_1_input_ETC__q7 =
	      inputFIFO_data_1;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        byte_count <= `BSV_ASSIGNMENT_DELAY 3'd0;
	inputFIFO_clearReq_ehrReg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	inputFIFO_deqP <= `BSV_ASSIGNMENT_DELAY 1'd0;
	inputFIFO_deqReq_ehrReg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	inputFIFO_empty <= `BSV_ASSIGNMENT_DELAY 1'd1;
	inputFIFO_enqP <= `BSV_ASSIGNMENT_DELAY 1'd0;
	inputFIFO_enqReq_ehrReg <= `BSV_ASSIGNMENT_DELAY 5'd10;
	inputFIFO_full <= `BSV_ASSIGNMENT_DELAY 1'd0;
	outputFIFO_clearReq_ehrReg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	outputFIFO_deqP <= `BSV_ASSIGNMENT_DELAY 1'd0;
	outputFIFO_deqReq_ehrReg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	outputFIFO_empty <= `BSV_ASSIGNMENT_DELAY 1'd1;
	outputFIFO_enqP <= `BSV_ASSIGNMENT_DELAY 1'd0;
	outputFIFO_enqReq_ehrReg <= `BSV_ASSIGNMENT_DELAY 25'd11184810;
	outputFIFO_full <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (byte_count$EN)
	  byte_count <= `BSV_ASSIGNMENT_DELAY byte_count$D_IN;
	if (inputFIFO_clearReq_ehrReg$EN)
	  inputFIFO_clearReq_ehrReg <= `BSV_ASSIGNMENT_DELAY
	      inputFIFO_clearReq_ehrReg$D_IN;
	if (inputFIFO_deqP$EN)
	  inputFIFO_deqP <= `BSV_ASSIGNMENT_DELAY inputFIFO_deqP$D_IN;
	if (inputFIFO_deqReq_ehrReg$EN)
	  inputFIFO_deqReq_ehrReg <= `BSV_ASSIGNMENT_DELAY
	      inputFIFO_deqReq_ehrReg$D_IN;
	if (inputFIFO_empty$EN)
	  inputFIFO_empty <= `BSV_ASSIGNMENT_DELAY inputFIFO_empty$D_IN;
	if (inputFIFO_enqP$EN)
	  inputFIFO_enqP <= `BSV_ASSIGNMENT_DELAY inputFIFO_enqP$D_IN;
	if (inputFIFO_enqReq_ehrReg$EN)
	  inputFIFO_enqReq_ehrReg <= `BSV_ASSIGNMENT_DELAY
	      inputFIFO_enqReq_ehrReg$D_IN;
	if (inputFIFO_full$EN)
	  inputFIFO_full <= `BSV_ASSIGNMENT_DELAY inputFIFO_full$D_IN;
	if (outputFIFO_clearReq_ehrReg$EN)
	  outputFIFO_clearReq_ehrReg <= `BSV_ASSIGNMENT_DELAY
	      outputFIFO_clearReq_ehrReg$D_IN;
	if (outputFIFO_deqP$EN)
	  outputFIFO_deqP <= `BSV_ASSIGNMENT_DELAY outputFIFO_deqP$D_IN;
	if (outputFIFO_deqReq_ehrReg$EN)
	  outputFIFO_deqReq_ehrReg <= `BSV_ASSIGNMENT_DELAY
	      outputFIFO_deqReq_ehrReg$D_IN;
	if (outputFIFO_empty$EN)
	  outputFIFO_empty <= `BSV_ASSIGNMENT_DELAY outputFIFO_empty$D_IN;
	if (outputFIFO_enqP$EN)
	  outputFIFO_enqP <= `BSV_ASSIGNMENT_DELAY outputFIFO_enqP$D_IN;
	if (outputFIFO_enqReq_ehrReg$EN)
	  outputFIFO_enqReq_ehrReg <= `BSV_ASSIGNMENT_DELAY
	      outputFIFO_enqReq_ehrReg$D_IN;
	if (outputFIFO_full$EN)
	  outputFIFO_full <= `BSV_ASSIGNMENT_DELAY outputFIFO_full$D_IN;
      end
    if (inputFIFO_data_0$EN)
      inputFIFO_data_0 <= `BSV_ASSIGNMENT_DELAY inputFIFO_data_0$D_IN;
    if (inputFIFO_data_1$EN)
      inputFIFO_data_1 <= `BSV_ASSIGNMENT_DELAY inputFIFO_data_1$D_IN;
    if (outputFIFO_data_0$EN)
      outputFIFO_data_0 <= `BSV_ASSIGNMENT_DELAY outputFIFO_data_0$D_IN;
    if (outputFIFO_data_1$EN)
      outputFIFO_data_1 <= `BSV_ASSIGNMENT_DELAY outputFIFO_data_1$D_IN;
    if (tempPixel_0$EN) tempPixel_0 <= `BSV_ASSIGNMENT_DELAY tempPixel_0$D_IN;
    if (tempPixel_1$EN) tempPixel_1 <= `BSV_ASSIGNMENT_DELAY tempPixel_1$D_IN;
    if (tempPixel_2$EN) tempPixel_2 <= `BSV_ASSIGNMENT_DELAY tempPixel_2$D_IN;
    if (tempPixel_3$EN) tempPixel_3 <= `BSV_ASSIGNMENT_DELAY tempPixel_3$D_IN;
    if (tempPixel_4$EN) tempPixel_4 <= `BSV_ASSIGNMENT_DELAY tempPixel_4$D_IN;
    if (tempPixel_5$EN) tempPixel_5 <= `BSV_ASSIGNMENT_DELAY tempPixel_5$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    byte_count = 3'h2;
    inputFIFO_clearReq_ehrReg = 1'h0;
    inputFIFO_data_0 = 4'hA;
    inputFIFO_data_1 = 4'hA;
    inputFIFO_deqP = 1'h0;
    inputFIFO_deqReq_ehrReg = 1'h0;
    inputFIFO_empty = 1'h0;
    inputFIFO_enqP = 1'h0;
    inputFIFO_enqReq_ehrReg = 5'h0A;
    inputFIFO_full = 1'h0;
    outputFIFO_clearReq_ehrReg = 1'h0;
    outputFIFO_data_0 = 24'hAAAAAA;
    outputFIFO_data_1 = 24'hAAAAAA;
    outputFIFO_deqP = 1'h0;
    outputFIFO_deqReq_ehrReg = 1'h0;
    outputFIFO_empty = 1'h0;
    outputFIFO_enqP = 1'h0;
    outputFIFO_enqReq_ehrReg = 25'h0AAAAAA;
    outputFIFO_full = 1'h0;
    tempPixel_0 = 4'hA;
    tempPixel_1 = 4'hA;
    tempPixel_2 = 4'hA;
    tempPixel_3 = 4'hA;
    tempPixel_4 = 4'hA;
    tempPixel_5 = 4'hA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkSerializerBTP

