// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  CommTypes::Byte
// Generated on: Wed May 04 02:44:11 EDT 2016
// Bluespec version: 2014.07.A 2014-07-30 34078

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<4> to Byte
typedef BitT<4> Byte ;

