// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  Clocks::ClkNextRdy
// Generated on: Thu Apr 28 19:21:26 EDT 2016
// Bluespec version: 2014.07.A 2014-07-30 34078

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<1> to ClkNextRdy
typedef BitT<1> ClkNextRdy ;

