// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  MemTypes::DDR3Addr
// Generated on: Wed Mar 16 01:34:20 EDT 2016
// Bluespec version: 2014.07.A 2014-07-30 34078

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<24> to DDR3Addr
typedef BitT<24> DDR3Addr ;

