// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  All SceMi types
// Generated on: Wed May 04 02:44:12 EDT 2016
// Bluespec version: 2014.07.A 2014-07-30 34078

#pragma once

#include "PowerStruct.h" 
#include "PowerAssoc.h" 
#include "ProbeControl.h" 
#include "PrbNum.h" 
#include "CosimStruct.h" 
#include "PowerProbe.h" 
#include "PwPrbKind.h" 
#include "ToHost.h" 
#include "FromHost.h" 
#include "SimulationControlReq.h" 
#include "SimulationStatusResp.h" 
#include "Mem_data_t.h" 
#include "Tag.h" 
#include "Exception.h" 
#include "Byte.h" 
#include "CacheWordSelect.h" 
#include "DDR3ByteEn.h" 
#include "Addr.h" 
#include "Data.h" 
#include "Instruction.h" 
#include "TLPFirstDWBE.h" 
#include "TLPLastDWBE.h" 
#include "CreditCount.h" 
#include "Lag.h" 
#include "ClkNextRdy.h" 
